# Generated by Django 3.2.9 on 2022-01-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='AMT',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='Discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='IMG',
            field=models.CharField(default=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='ProductID',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='studyroom',
            name='Title',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
