# Generated by Django 3.2.9 on 2022-01-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20220110_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livingroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.IntegerField(default=True)),
                ('Title', models.CharField(default=True, max_length=500)),
                ('AMT', models.FloatField(default=True)),
                ('Discount', models.IntegerField(null=True)),
                ('IMG', models.CharField(default=True, max_length=2500)),
            ],
        ),
        migrations.DeleteModel(
            name='living',
        ),
    ]
