# Generated by Django 3.2.9 on 2022-01-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20220110_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livingroom',
            name='IMG',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='livingroom',
            name='Title',
            field=models.CharField(max_length=500),
        ),
    ]
